<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Phantom.UI</RootNamespace>
    <AssemblyName>Phantom.Injector</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Phantom.Core\Phantom.Core.csproj" />
  </ItemGroup>

</Project>
